### ISSUE TITLE
No Update Button

### ISSUE THREAD

**Issue by Aliking1990** [Dhruv-Techapps/auto-click-auto-fill#101]
Hello!

I have Auto Click Pro version but there is no Update button. How can I activate my auto click? And can I use full xPath copy?

**Comment by Dhruv-Techapps** [comment]
Once you have done [subscription](https://getautoclicker.com/docs/subscription) from one of two available methods.
Google Payment - no need to update. It will auto enable the subscription and you need to switch on pro switch in order to make use of same.
Paypal Payment - you need to click on check registration in order to enable subscription
