### ISSUE TITLE
Retry Interval of a split second

### ISSUE THREAD

**Issue by Nephin** [Dhruv-Techapps/auto-click-auto-fill#110]
I'd love to be able to set Retry Interval to less than one second but the field does not accept symbols, only digits.

I use the extension for work but for the project I'm working on, the frequency of 1 second is not enough. I'm aware of extensions for thousand clicks per second, I'm not talking about this. Auto Click Auto Fill is excellent for me, but would be just perfect if I can set Retry Interval to let's say 0.1 sec. or at least 1/2 sec.

Can something be done with this please?

**Comment by Dhruv-Techapps** [comment]
You can try adding interval less than `1` sec using `0.5` sec and If you want speeder than that leave it blank as it will start as soon as it come in action.

usually an action takes 100-400 milliseconds to perform it, based on system configuration

https://getautoclicker.com/docs/action#repeat-interval

**Comment by Nephin** [comment]
Thank you for the answer, but it's not the point. The "R-Interval" next to an Action means **Repeat**, ie. how many times and at what speed it will be performed _succesfully_.
What I'm asking for, is **Retry** Interval in the Settings, which means how many times and at what speed it will _try to find_ the x-path. And this one I cannnot set to less than second. I'm on Pro subsciption.

**Comment by Dhruv-Techapps** [comment]
@Nephin **Thank you for subscribing our extension**

For [retry-interval](https://getautoclicker.com/docs/settings#retry-interval) also you add `0.5` as value or `0` to start right away. 

`0.1` is also valid value, but to process `waiting` instruction by the system, it has to go into memory and ready back when times up. It can take up to 200-300 milliseconds. This will either require a very high machine to work accurately, or no other process should run in the background so that system gives no 1 priority to this task and try to accomplish in require time.

**Comment by Nephin** [comment]
I can do this only in:
- Batch init wait
- Init Wait
- Action R-Interval

I cannot do this where it's needed: Settings -> Retry Interval. 

I'm using v2.1.1, Widows 10, Chrome

**Comment by Nephin** [comment]
I tried the chrome extension in Kiwi Browser on my android tablet, and I can do this there in the Settings. So where could be the problem on Windws/Chrome?

**Comment by Nephin** [comment]
SOLVED!! I foud a walkaround. I caanot TYPE the period in the settings, but I can PASTE a value with it.

**Comment by Dhruv-Techapps** [comment]
Thank you. We will create a separate issue for this and fix it.

Thank you once again.
