### ISSUE TITLE
Option not getting selected in a dropdown

### ISSUE THREAD

**Issue by iamgurung** [Dhruv-Techapps/auto-click-auto-fill#132]
All other input types seem to be working though. Have you checked it recently ?

**Comment by dhruv-choudary** [comment]
Hi @iamgurung ,

we have tested with below configuration using [DEV version](https://chrome.google.com/webstore/detail/cpjikgcdmhfnmaiibplplldlchbjejel?authuser=0&hl=en)

**URL** - https://test.getautoclicker.com/
**Action** - //select[@name="cars"]
**Value** - fiat

### you need to set dropdown value instead of dropdown name 

e.g. if you want to select `Audi` you need to provide `audi` in value field

![image](https://user-images.githubusercontent.com/75973635/103147935-10e8a480-4780-11eb-8670-6c431153bfb4.png)

#### Do check and let us know if you still face issue

**Comment by FanchenBao** [comment]
I think this should be included in the documentation. I followed the instruction in [Select Option](https://getautoclicker.com/docs/3.x/action/value/#select-option), but that only allows the dropdown to show the selected item but not actually click it. In order to select the item **AND** click it to trigger some more actions, I need to use the set up mentioned in the post above with `value` set to the value defined in the option tag.
