### ISSUE TITLE
display enable status for configs on dropdown lsit 

### ISSUE THREAD

**Issue by tksoh** [Dhruv-Techapps/auto-click-auto-fill#146]
Right now the dropdown list of the configurations does not indicate if a config is enabled/disabled, so we have to cycle through each of them to find out, which can be very tiring if we have a lot of configs.  

I would like to suggest if some kind of indication can be add to the dropdown list to provide the indication.  Or perhaps or add the ability to filter the configs by their status at the same time.

Thanks for your consideration. And keep up the great work 👍

**Comment by PerryFromHolland** [comment]
Great suggestion! 
Would be an absolute enhancement

**Comment by dhruv-choudary** [comment]
Thank you @tksoh for suggestion . we will bring above changes in upcoming release.

**Comment by dharmesh-hemaram** [comment]
This issue is fixed and now available with [DEV v3.1.9](https://chrome.google.com/webstore/detail/auto-clicker-autofill-dev/cpjikgcdmhfnmaiibplplldlchbjejel)

<img width="1139" alt="Screenshot 2021-01-25 at 2 52 29 PM" src="https://user-images.githubusercontent.com/2290202/105687172-23d8cb00-5f1e-11eb-8670-2f594232bd0e.png">
