### ISSUE TITLE
changeable url

### ISSUE THREAD

**Issue by androidkade11** [Dhruv-Techapps/auto-click-auto-fill#94]
Hi
The settings for the fixed page are fine, but I want to use the page whose url changes

**Comment by Dhruv-Techapps** [comment]
Can you please provide some sample of URLs. Our extension support regex patters to check URL.

[docs](https://getautoclicker.com/docs/configuration#url)

**Comment by androidkade11** [comment]
‫‪Dhruv-Techapps‬‏ <‪notifications@github.com‬‏> در تاریخ دوشنبه ۱۳ ژانویهٔ
۲۰۲۰ ساعت ۱۳:۵۶ نوشت:‬

**Comment by gyalbu** [comment]
Say if we set the extension for an autologin into a site. So first the url would be like http: //www.site.com/login and the we want the extension to continue then the url would have changed to something like http: //site.com/admin. So the plugin throws error that it cant find the element. It is obvious because the configuration is set for http: //www.site.com/login only.

@ghost the link you provided gives a 404.
